#ifndef N2SCFTDB_INDEX_EXPAND_HPP
#define N2SCFTDB_INDEX_EXPAND_HPP

#include <cstdint>
#include <map>
#include <vector>

#include <gmpxx.h>

namespace n2scftdb {

using IndexedMonomial = std::vector<int>;
using MatterMultiplicities = std::map<IndexedMonomial, mpz_class>;

struct CharacterPowers {
    int character;
    // Entry j-1 is the exponent of C_character(j). As in the Python FORM
    // parser, length is sum(j * exponent), including trailing zero entries.
    std::vector<std::int64_t> adams_powers;
};

struct IndexFormTerm {
    mpq_class coefficient;
    int t_power;
    std::int64_t y_power;
    std::int64_t u_power;
    std::vector<CharacterPowers> characters;
};

// Exact formal expansion of the program generated by _build_form_program.
// Inputs have the same meaning and order as that Python function:
//   order: inclusive nonnegative t cutoff;
//   character_count: number of formal characters C0,...,C(character_count-1);
//   vector_characters: one character index per vector letter;
//   matter_multiplicities: product of character indices -> integer multiplicity.
// An empty matter monomial is a gauge singlet. Repeated indices, zero/signed
// multiplicities, and arbitrarily large integer multiplicities are supported.
// Indices must lie in [0, character_count), including in zero-multiplicity data.
//
// Returns nonzero terms, with reduced exact rational coefficients, ordered by
// (t_power, y_power, u_power, characters). Characters are sorted by index and
// use the same Adams-power convention as Python's IndexFormTerm. FORM's printed
// order is not preserved. Cutoffs 0 and 1 return the vacuum term 1.
//
// No FORM process, disk cache, Python runtime, or character decomposition is
// involved. All working data is local to the call. Requires C++17 and GMP
// (gmpxx/gmp), compiled and linked with -pthread.
// Invalid counts/indices throw std::invalid_argument; exponent
// overflow throws std::overflow_error; allocation failures propagate.
std::vector<IndexFormTerm> expand_index(
    int order,
    int character_count,
    const std::vector<int>& vector_characters,
    const MatterMultiplicities& matter_multiplicities);

// Same exact result with up to worker_count computation threads, including
// the calling thread. worker_count must be positive; 1 is the serial path
// used by the four-argument overload. Small workloads run serially, and fewer
// threads are used when there are fewer independent tasks. Each degree is
// completed before the next; workers own independent polynomial accumulators.
// Threads are reused within this call and joined before return or rethrowing
// a worker exception. Parallel work can require more temporary memory.
std::vector<IndexFormTerm> expand_index(
    int order,
    int character_count,
    const std::vector<int>& vector_characters,
    const MatterMultiplicities& matter_multiplicities,
    int worker_count);

}  // namespace n2scftdb

#endif
